easy_admin:
    entities:
#        # List the entity class name you want to manage
        - App\Entity\Maladie
        - App\Entity\User
        - App\Entity\Specialiste
        - App\Entity\RendezVous
        - App\Entity\Admin
